### ISSUE TITLE
App logo is missing

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#1]
Please keep app logo for the app.

**Comment by ijazakram** [comment]
@Prasad, Please provide APP logo and other details from the PSD. If those are not available please update to Client ON immediate process.

**Comment by PrasadSamana** [comment]
@ijazakram, Done Logo provided and all screens details provided

**Comment by KrishnaVittal** [comment]
Guest App logo is missing...
