### ISSUE TITLE
Web -New Dispatch call - updation (Edit) is not working

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#10]
Click on New dispatch call - select on record and click on edit button then "call updation  failed" message is displaying. Please check the image below...
![updating call](https://user-images.githubusercontent.com/45225727/48966894-c293d500-effe-11e8-84b3-6d85720ccf92.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal I have fixed this issue in the development serves and now updating functionality working fine. But some UI changes are there. For now, please close this issue and raise new issues for UI conflicts.
