### ISSUE TITLE
Web - One driver is register in one towing company again that driver wont allow to register in other towing company

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#118]
One driver is register in one towing company again that driver wont allow to register in other towing company(Same mobile number).
![driversamephonenumberin2towing](https://user-images.githubusercontent.com/45225727/49988472-cdf27480-ff9c-11e8-9eef-6e6127d4f0da.PNG)

**Comment by ijazakram** [comment]
As per my knowledge, this bug may not exist in the real-time. Individual towing companies should contain respective Drivers with UNIQUE mobile numbers. If any Driver exists in two different Toying companies then, he personally installs two different white labeling apps. 

I hope this bug may not reproduce in the live scenarios. Please ignore this bug.
