### ISSUE TITLE
Web - New Dispatch Call - Enter data in Plate number

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#12]
Enter data in plate number its showing two long white boxes. Please check the image.
![plate number](https://user-images.githubusercontent.com/45225727/48967553-5322e300-f008-11e8-8a40-fe18070ec1c5.png)

**Comment by ijazakram** [comment]
@PrasadSamana Please look into this issue and support us.

**Comment by PrasadSamana** [comment]
Issue cleared

**Comment by KrishnaVittal** [comment]
Issue is fixed but empty box is displaying. Please mention "No data found"
