### ISSUE TITLE
driver App - Dispatch call - on scene - add picture - camera is opening  but click on the button, nothing is happening.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#122]
Dispatch call - on scene - add picture - camera is opening  but click on the button, nothing is happening.
![whatsapp image 2018-12-17 at 10 48 56 am](https://user-images.githubusercontent.com/45225727/50067985-a6dcb280-01e9-11e9-8028-156cb8dbc528.jpeg)

**Comment by shankar7893** [comment]
in react native it takes time to save image and convert it to base64 so it is taking 4 to 7 sec
