### ISSUE TITLE
Web -Rent Roll Registration -Update 

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#13]
Select the Rent roll from the rent roll table and click on edit, then update data and click on update button then its not updating. Click update again then its updating.
![updaterentroll](https://user-images.githubusercontent.com/45225727/48968827-2fb56380-f01b-11e8-8cbc-24a9df3d043e.PNG)

**Comment by ijazakram** [comment]
I have fixed this issue, please check and close.

**Comment by ijazakram** [comment]
Do not create duplicate bugs. I have resolved this issue.
