### ISSUE TITLE
Web -Rent Roll Registration -Update - Not updating immediatly in the rent roll table

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#14]
Edit the rent roll and click on update then the data is updating but in the rent roll table its not updating. After refreshing the page its updating.

Note: Update for first time then and click on edit again, then the already message in the update page is still displaying.
![afterupdaterentroll](https://user-images.githubusercontent.com/45225727/48968918-2b3d7a80-f01c-11e8-9cfc-3b8a8b7d4783.PNG)

**Comment by KrishnaVittal** [comment]
![updaterentroll](https://user-images.githubusercontent.com/45225727/48968923-3ee8e100-f01c-11e8-9300-4095df8e9f1d.PNG)

**Comment by ijazakram** [comment]
I have resolved this issue. Please review and close this bug.

**Comment by KrishnaVittal** [comment]
Update the details but not immediately its not updating in rent roll list. After refreshing the page its updating.
