### ISSUE TITLE
web - driver - edit driver - add 91 to the phone number - otherwise user cannot edit the phone number

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#166]
driver - edit driver - add 91 to the phone number - otherwise user cannot edit the phone number

**Comment by ijazakram** [comment]
it's not required. take this action only at mobile append for a temporary purpose. By default, all drivers should points to U.S.A

**Comment by KrishnaVittal** [comment]
but now its impossible to edit the driver. if we want to change the mobile number. we have to create new driver.

**Comment by ijazakram** [comment]
why?
