### ISSUE TITLE
Towing company login/All screens -But it's inappropriate labels/selection in most of the pages, Pls revisit each page guide and try to fix it.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#177]
Page guide walk through looks very good, But it's inappropriate labels/selection in most of the pages, Please revisit each page guide and try to fix it.

**Comment by nareshgali** [comment]
There is a problem with the used plugin (EnjoyHint).Customization of walkthrough like changing position of text/arrow etc cant be changed.where there is a problem with plugin(particular section) please think and review that whether walkthrough at that section is required or not.
