### ISSUE TITLE
Web - View Rent Roll List - Phone Numbers names are displaying as Phone_number. Remove underscore, then user can read that name easily

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#18]
Please display the data in readable mode to the user.. Please remove Phone_number, Phone_number1, phone_number2 in view rent roll 
![displayphone_notophonenumber](https://user-images.githubusercontent.com/45225727/48995121-a3b35100-f16c-11e8-8f6a-698cd10b49b8.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal it's very important to display. Please close this thread.
