### ISSUE TITLE
Towing company login/Property registration/Spaces Info - Guest spaces field is auto calculating or generated field, But it's allowing cursor to enter and also showing as mandatory field when value is blank

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#187]
Guest spaces field is auto calculating or generated field, But it's allowing cursor to enter and also showing as mandatory field when value is blank

**Comment by nareshgali** [comment]
Yeah...as per requirement (referred from pass2parktx) guest spaces should be auto calculated and it is a mandatory field to fill.There is no issue in this.
