### ISSUE TITLE
Towing company login/Property registration/Spaces Info - Parking Time limit field some times goes unproper order of the fields in space info section (as new line)

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#188]
Parking Time limit field some times goes unproper order of the fields in space info section (as new line)

**Comment by nareshgali** [comment]
@KrishnaVittal if any UI issues are there,please assign  them to @PrasadSamana

**Comment by KrishnaVittal** [comment]
![propertyregistrationdesign](https://user-images.githubusercontent.com/45225727/50726867-e176a280-1138-11e9-939a-8150e455d531.PNG)
