### ISSUE TITLE
Towing company login/Dispatch/New Dispatch Call - is it necessary to allow fields to enter details!

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#205]
New Dispatch call registration source info showing mandatory field message for all the fields in source info section. But when we select the Property from the list, it's auto filling the details. Do we think is it necessary to allow fields to enter details!

**Comment by nareshgali** [comment]
Yes, user is always allowed to enter all fields of source info section.because in next scope we are going to provide custom source address entry, at that time allow of entering fields are mandatory.
