### ISSUE TITLE
Web - Super admin login - After Logout and click go back, then click on refesh, then again click on enter server error is displaying

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#215]
Super admin login - After Logout and click go back, then click on refesh, then again click on enter server error is displaying
![backbuttonafterclickthenagainenter](https://user-images.githubusercontent.com/45225727/50752048-7335fb00-1272-11e9-94fc-0223cbea7e59.PNG)
![backbuttonclickthen1](https://user-images.githubusercontent.com/45225727/50752049-7335fb00-1272-11e9-8c68-9767441e0221.PNG)

**Comment by nareshgali** [comment]
@ijazakram Please review this issue and let me suggest for fix.i need your help here.
