### ISSUE TITLE
Web - Dispatch Call List - with same plate number two records are displaying.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#22]
Dispatch Call List - with same plate number two records are displaying. Please check it..
![withsameplatenumbers2recordsdisplaying](https://user-images.githubusercontent.com/45225727/49060131-2e11b880-f232-11e8-9213-d43bb9b630e9.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal I think, there is possibility for this use - case. 
@VisuDR @nareshgali Please suggest on this.

I think, its not a bug.

**Comment by VisuDR** [comment]
Yes, same License plate can be towed multiple times..
But in this case both the records are at the same time, it seems like a Duplicate record

**Comment by ijazakram** [comment]
Its OK !!! In testing they may created. !!!!!
