### ISSUE TITLE
Web - For all the edit screens - no need of reset button, replace it with cancel button.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#31]
For all the edit screens - no need of reset button, replace it with cancel button.  And user click on cancel button its redirect back to back page.

**Comment by ijazakram** [comment]
@KrishnaVittal It's not required RESET buttons for EDIT functionality its wrong UI indication. please close this issue. If he wants to remove over all things, please DELETE and CREATE a NEW one. 

For now, I am closing this issue.
