### ISSUE TITLE
Web - Dispatch call list - newly added record has to display first.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#32]
Dispatch call list - newly added record has to display first.

**Comment by ijazakram** [comment]
@KrishnaVittal not newly added record display first. We would like to display first processing Calls as first priority. please check in that way.

**Comment by VisuDR** [comment]
Is it possible to have the same tabs as in Driver App..
Pending - Active - Completed

**Comment by ijazakram** [comment]
@VisuDR It's better to display on the all status functionality instead of this. The web is different compared to the mobile app.

**Comment by VisuDR** [comment]
So by this can I understand it like this..
The record with latest status change, displays first?

**Comment by ijazakram** [comment]
YES
