### ISSUE TITLE
Web - Click on dispatch - Displaying error message

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#33]
Click on dispatch - Displaying error message. Please check the screenshot
![dispatcherromessage](https://user-images.githubusercontent.com/45225727/49072030-519a2a80-f255-11e8-83a5-7d320bd247ad.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal @VisuDR  I am unable to see this issue ....................
