### ISSUE TITLE
Web - Dashboard - Rent Roll count displaying wrong.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#36]
Dashboard - Rent Roll count displaying wrong. it has 3 records its displaying as 2.
Note: If we click on view rent roll link then its showing in-active rent roll as 21. but total 3 records are available. Please check the screenshot.

![rentroll](https://user-images.githubusercontent.com/45225727/49085108-40faac00-f277-11e8-94ce-e38f15665c8e.PNG)
![wronginactiverentroll](https://user-images.githubusercontent.com/45225727/49085117-45bf6000-f277-11e8-809a-d6a24c0ecc0f.PNG)

**Comment by KrishnaVittal** [comment]
![rentrollactualcount](https://user-images.githubusercontent.com/45225727/49085305-bcf4f400-f277-11e8-8414-fe52258a1ccf.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal I have fixed this issue. please check once.
