### ISSUE TITLE
Web - Need tool-tip(hover) for all the action buttons.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#37]
Need tool-tip (hover) for all the action buttons.

**Note: For action buttons no need of sorting.(Dispatch calls list).**
![dispatchcall -sortingonactionnoneed](https://user-images.githubusercontent.com/45225727/49086086-b2d3f500-f279-11e8-9a7f-7ce4c10ae310.PNG)

**Comment by nareshgali** [comment]
Added tooltips in all logins(modules)
