### ISSUE TITLE
Web - Dashboard - Driver images is not displaying properly.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#46]
Dashboard - Driver images is not displaying properly in "Latest Driver Dispatches"
![webdriverdispatchimagenotdisplayingcorrectly](https://user-images.githubusercontent.com/45225727/49148946-c725f980-f32e-11e8-9aae-5439668c6e8b.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal I know this bug & how to fix at the mobile end, for the temporary fix, please upload your picture in the proper direction.

**Comment by ijazakram** [comment]
@shankar7893 send images as 200 X 200 sizes to fix this issue.
