### ISSUE TITLE
Driver App - Edit Profile - Mobile number is displaying wrong.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#47]
![whatsapp image 2018-11-28 at 6 49 08 pm](https://user-images.githubusercontent.com/45225727/49154497-80400000-f33e-11e8-8422-58e503055fc5.jpeg)
Edit Profile - Mobile number is displaying wrong.

**Comment by ijazakram** [comment]
@shankar7893 mobile number has shared now. check once.
