### ISSUE TITLE
Web - Edit Driver - Phone number is not editable.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#48]
Edit Driver - Phone number is not editable. (its should be editable).
![drivereditphonenumbernotediting](https://user-images.githubusercontent.com/45225727/49205240-67822980-f3d4-11e8-985d-96b69ef93b92.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal Phone number is unique. Isn't it?

**Comment by KrishnaVittal** [comment]
No Akram, its should be editable, That person is towing company admin. So he can edit.

**Comment by ijazakram** [comment]
resolved. check and close.
