### ISSUE TITLE
Guest App - Guest Parking Approved - Cancel it is not working.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#49]
Guest Parking Approved - Cancel it is not working. If user select the cancel it button then it cancel the guest registration. In guest history (WEB) - it has to show as cancelled

**Comment by KrishnaVittal** [comment]
From the guest app -user click on cancel it button then - in the guest history (web) still showing as active status. (Shankar told its working fine from his side..)...
![guesthstystatusnotupdatingweb](https://user-images.githubusercontent.com/45225727/49278574-3cb6d480-f4ab-11e8-90b3-68c628eed6d0.PNG)

**Comment by nareshgali** [comment]
Checked and didnt find any issue in web...need to check with shankar....
