### ISSUE TITLE
Web - Login - Remember me check box is not working

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#55]
Login - Remember me check box is not working
![remember me](https://user-images.githubusercontent.com/45225727/49328976-e1660e80-f59e-11e8-906d-ef1b2c1a965f.PNG)

**Comment by nareshgali** [comment]
Going to remove remember option from form..will be implemented(phase II) if client requires that feature.
Lets complete the actual flow functionality first..anyway iam resolving this issue from end
