### ISSUE TITLE
Driver APP - History (Activity Log) - Call id has to display

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#56]
History (Activity Log) - Call id has to display.
 Change - Call Accepted to  - #call id Dispatch Call Accepted.

![whatsapp image 2018-12-01 at 7 37 21 pm](https://user-images.githubusercontent.com/45225727/49329129-9f3dcc80-f5a0-11e8-9f28-40824cb59f97.jpeg)

**Comment by shankar7893** [comment]
Need data from api

**Comment by nareshgali** [comment]
![s1](https://user-images.githubusercontent.com/43168925/49700593-bb77e400-fc06-11e8-942d-43dbaa1123cc.PNG)
API updated.for reference check attached screenshot
