### ISSUE TITLE
Web - Company profile -change password - current password - spelling wrong in popup window

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#63]
Company profile -change password - current password - spelling wrong in popup window. Please check the screen shot.
![companyprofilespellingwrong](https://user-images.githubusercontent.com/45225727/49372547-0da99880-f721-11e8-90a1-cb7562816e0a.PNG)

**Comment by nareshgali** [comment]
changed message to "Current password is not matched"
