### ISSUE TITLE
Driver App - Verification screen, Please change the message.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#65]
Verification screen, Please change the message. "Invalid OTP,please enter valid one" change to "Invalid OTP !, Please enter valid one".
![whatsapp image 2018-12-05 at 10 53 20 am](https://user-images.githubusercontent.com/45225727/49491914-12cf2a80-f87c-11e8-9867-8e19b8f190d8.jpeg)

**Comment by VisuDR** [comment]
"Please Enter the Valid OTP! "
should be fine rather making it as two statements

**Comment by ijazakram** [comment]
Thanks for the bug. I have fixed this issue, please review and close this one.

**Comment by KrishnaVittal** [comment]
User without enter the OTP, we cant show "Please enter the valid OTP",we have to show the message (alert) as "Please enter OTP ! then if user enter any OTP then we have to show the message "Please enter the valid OTP"

**Comment by nareshgali** [comment]
If user dont enter any OTP then app side alert should be shown..no need to come to server and response back with Please enter OTP.

So please think about it..iam resolving this issue from my end

**Comment by VisuDR** [comment]
@shankar7893 better handle this on the app side, if the OTP not entered fully/entered partial prompt the user to enter OTP saying "Please Enter OTP to Proceed Further"(message can be altered)
