### ISSUE TITLE
Driver App - Dispatch - Call Details - License# will have to display full license plate number

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#66]
Dispatch - Call Details - License# will have to display full license plate number. Please check the screenshot.
![whatsapp image 2018-12-05 at 11 04 01 am](https://user-images.githubusercontent.com/45225727/49492267-9ccbc300-f87d-11e8-9bc5-1cf21c1da5a0.jpeg)

**Comment by ijazakram** [comment]
@all Yes we have display for complete LIC number in the detailed CALL pages.
