### ISSUE TITLE
Driver App - Dispatch - Pending list - Showing car color as empty.. 

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#67]
Dispatch - Pending list - Showing car color as empty..  please check the screenshot.
![whatsapp image 2018-12-05 at 11 16 44 am](https://user-images.githubusercontent.com/45225727/49492749-9dfdef80-f87f-11e8-9ee5-a60004902efe.jpeg)

Note: Shankar created the sample dispatch call from web, then he enter all the mandatory fields and click created then the color and van numbers are not saved.
![colorandvannotdisplaying](https://user-images.githubusercontent.com/45225727/49492826-df8e9a80-f87f-11e8-963d-dbf7ec477356.PNG)

**Comment by nareshgali** [comment]
Car color is not a mandatory field

**Comment by nareshgali** [comment]
@ijazakram shall we make every vehicle info field as mandatory

**Comment by ijazakram** [comment]
@nareshgali Yes make it as mandatory.
