### ISSUE TITLE
Driver App - Side menu - Beside driver name - display his status (On work)

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#68]
Side menu - Beside driver name - display his status (On work). Like this we have to display.

![driverstatusdisplay](https://user-images.githubusercontent.com/45225727/49494120-8f660700-f884-11e8-816f-8c36314f0e41.PNG)

Currently we are displaying like this
![whatsapp image 2018-12-05 at 11 52 11 am 1](https://user-images.githubusercontent.com/45225727/49494165-adcc0280-f884-11e8-9efa-31c9cefe7d8b.jpeg)

**Comment by shankar7893** [comment]
For this i need status from api
