### ISSUE TITLE
driver app - Profile picture is not displaying after user logout and again login.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#71]
Edit profile - user update the profile picture then save it and then logout the application and again login, the updated profile picture is not displaying, its displaying empty.
![whatsapp image 2018-12-01 at 7 53 37 pm](https://user-images.githubusercontent.com/45225727/49641682-e6abd900-fa36-11e8-8dcd-80eefc0de30e.jpeg)

**Comment by KrishnaVittal** [comment]
Note: same in edit profile also.

**Comment by shankar7893** [comment]
For that i need image data from api

**Comment by nareshgali** [comment]
Updated API given
