### ISSUE TITLE
Web - Login with new towing company details - getting error message.

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#81]
Login with new towing company details - getting error message.
![newtowcompanyuserlogin](https://user-images.githubusercontent.com/45225727/49713646-abe0b580-fc6f-11e8-9612-0eb080ff509b.PNG)

**Comment by ijazakram** [comment]
@KrishnaVittal  what are the user-name and passwords?

**Comment by KrishnaVittal** [comment]
Test Tow Company1
Email id -testtowcompany1@gmail.com
User name – towcompany1
Password -12345678
