### ISSUE TITLE
Web - Towing company user - Create property registration - Edit -all the selected parking rules are not displaying

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#85]
Towing company user - Create property registration - Edit -all the selected parking rules are not displaying
![editpropertyregistration-parkingrulesnotshowingallselectedrules](https://user-images.githubusercontent.com/45225727/49718931-996f7780-fc81-11e8-91a1-e0043e682992.PNG)

**Comment by nareshgali** [comment]
I checked it ..i didnt found this issue...i created property and edited and updated parking rules...

**Comment by KrishnaVittal** [comment]
while creating new property i selected 3 parking rules, No damaged  vehicles, no handicaped parking and no firelane parking then click ok create, then click on edit the parking rules its displaying only 1 selected rule.

**Comment by nareshgali** [comment]
please create one new property and check.if you again face same issue i will deeply check and fix it
