### ISSUE TITLE
Web - New Dispatch Call - Click on create button is not working for first time

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/Pass2parkIT#9]
Click on New dispatch call - Enter all the details and click on "Create" then  first time dispatch call is not working. Again click on create button then dispatch call is creating.

**Comment by ijazakram** [comment]
I have cross checked this issue multiple times in the development servers and failed to reproduce. Please share some more details on this issue and close if you failed to reproduce. 

I suspect you did not enter mandatory fields and then the issue has raised. Please check again.

**Comment by KrishnaVittal** [comment]
Hi Akram, the issue is reproduce and i update that details - Enter all the data with new values -New plate number and new vin number then try to click on create button.
